version: 0.2.{build}

image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
build:
  project: .\BatMap.sln
  verbosity: minimal
  
before_build:
  - nuget restore

after_build:
- dotnet pack BatMap\BatMap.csproj -c Release /p:Version=%appveyor_build_version%
- appveyor PushArtifact BatMap\bin\%CONFIGURATION%\BatMap.%appveyor_build_version%.nupkg
- BatMap.Benchmark\bin\%CONFIGURATION%\BatMap.Benchmark.exe

test_script:
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe -targetargs:BatMap.Tests\bin\%CONFIGURATION%\BatMap.Tests.dll -filter:"+[BatMap*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:opencoverCoverage.xml
- packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken "%COVERALLS_REPO_TOKEN%" --useRelativePaths --commitId "%APPVEYOR_REPO_COMMIT%" --commitBranch "%APPVEYOR_REPO_BRANCH%" --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId "%APPVEYOR_BUILD_NUMBER%" --serviceName appveyor

deploy:
  provider: NuGet
  api_key:
    secure: hQY0HMU8ADJvqFfivG/Z0+h2Nz8xFCFd64ERHhaTFc3SzRy3Kz8C3FE8tiJMqMjz
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
