version: 0.1.{build}

only_commits:
  files:
    - BatMap/
    - BatMap.Benchmark/
    - BatMap.Tests/

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
build:
  project: .\BatMap.sln
  verbosity: minimal
  
before_build:
  - nuget restore

after_build:
- nuget pack BatMap\BatMap.csproj -IncludeReferencedProjects -Version %appveyor_build_version%
- appveyor PushArtifact BatMap.%appveyor_build_version%.nupkg

test_script:
- ps: >-
    .\packages\OpenCover.*\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.ConsoleRunner.*\tools\nunit3-console.exe -targetargs:.\BatMap.Tests\bin\$env:CONFIGURATION\BatMap.Tests.dll /noshadow -filter:"+[BatMap*]*" -output:opencoverCoverage.xml
    
    $coveralls = (Resolve-Path "./packages/coveralls.net.*/tools/csmacnz.Coveralls.exe").ToString()
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

deploy:
  provider: NuGet
  api_key:
    secure: hQY0HMU8ADJvqFfivG/Z0+h2Nz8xFCFd64ERHhaTFc3SzRy3Kz8C3FE8tiJMqMjz
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
