version: 0.1.{build}
configuration: Release

before_build:
  - nuget restore
  
after_build:
- nuget pack BatMap\BatMap.nuspec -Version %appveyor_build_version%
- appveyor PushArtifact BatMap.%appveyor_build_version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: hQY0HMU8ADJvqFfivG/Z0+h2Nz8xFCFd64ERHhaTFc3SzRy3Kz8C3FE8tiJMqMjz
  skip_symbols: false
  artifact: /.*\.nupkg/
